engine: kafka
targets:
  - brokers: ["localhost:9092"]
    topic: taiko
    key: "{{user_id}}"
    value: '{"event": "click", "user": "{{user_id}}", "timestamp": "{{timestamp}}"}'
    rps: 5
load:
  duration: 10s
variables:
  - name: user_id
    type: uuid
  - name: timestamp
    type: timestamp
    generator:
      format: rfc3339